version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:
  go-113-5:
    docker:
      - image: circleci/golang:1.13.5-node
    working_directory: /go/src/github.com/kemokemo/try-circle-ci

jobs:
  test:
    executor: go-113-5
    steps:
      - checkout
      - run: go version
      - run: go get -v -t -d ./...
      - run: go test -v -cover -coverprofile=coverage.out ./...
      - codecov/upload:
          file: ./coverage.out
  build:
    executor: go-113-5
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build
  deploy:
    executor: go-113-5
    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - checkout
      - run: go get -v -t -d ./...
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: mkdir release
      - run: gox -output "./release/{{.Dir}}_{{.OS}}_{{.Arch}}"  ./ ./...
      - run: ghr -u $CIRCLE_PROJECT_USERNAME $CIRCLE_TAG release/

workflows:
  version: 2
  test and build:
    jobs:
      - test
      - build
  deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
